# Generated by Django 2.0 on 2019-09-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190514_1716'),
        ('blog', '0008_auto_20190422_0010'),
    ]

    operations = [
    ]
